Scorrere in basso per avere i log piu' recenti.
I Log vengono registrati ogni volta che viene lanciato il programma.


I seguenti Log fanno riferimento al giorno 22-10-2020 alle ore 14.45.37

ERRORE GENERALE: Traceback (most recent call last):
  File "c:\Users\Ali Haider Maqsood\Documents\GitHub\MAW\RinominaPdf\RinominarePdfDaInput.py", line 13, in <module>
    nomeExcel = returnFrame[0][0]
IndexError: list index out of range



I seguenti Log fanno riferimento al giorno 22-10-2020 alle ore 14.51.57

ERRORE GENERALE: Traceback (most recent call last):
  File "c:\Users\Ali Haider Maqsood\Documents\GitHub\MAW\RinominaPdf\RinominarePdfDaInput.py", line 13, in <module>
    nomeExcel = returnFrame[0][0]
IndexError: list index out of range



I seguenti Log fanno riferimento al giorno 22-10-2020 alle ore 14.53.13

ERRORE GENERALE: Traceback (most recent call last):
  File "c:\Users\Ali Haider Maqsood\Documents\GitHub\MAW\RinominaPdf\RinominarePdfDaInput.py", line 13, in <module>
    nomeExcel = returnFrame[0][0]
IndexError: list index out of range
